spring:
  datasource:
    url: postgresql://doadmin:AVNS_dltceQCRRkv37wt8hRZ@db-avantio-postgresql-do-user-14013830-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    enabled: true