#spring:
#  config:
#    import: optional:file:.env[.properties]
#  datasource:
#    url: ${DATABASE_URL}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#server:
#  port: 8080
#springdoc:
#  api-docs:
#    path: /api-docs
#    enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
#    url: /api-docs
#    enabled: true